# Generated by Django 2.2.1 on 2019-05-16 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者', 'verbose_name_plural': '作者'},
        ),
        migrations.AddField(
            model_name='author',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='价格'),
        ),
    ]
